package pojos;
// Generated May 6, 2018 4:40:33 PM by Hibernate Tools 4.3.1



/**
 * Admins generated by hbm2java
 */
public class Admins  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private String password;

    public Admins() {
    }

    public Admins(int id, String name, String email, String password) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


