package pojos;
// Generated May 6, 2018 4:40:33 PM by Hibernate Tools 4.3.1



/**
 * CarHasRoutesId generated by hbm2java
 */
public class CarHasRoutesId  implements java.io.Serializable {


     private int carsId;
     private int routesId;

    public CarHasRoutesId() {
    }

    public CarHasRoutesId(int carsId, int routesId) {
       this.carsId = carsId;
       this.routesId = routesId;
    }
   
    public int getCarsId() {
        return this.carsId;
    }
    
    public void setCarsId(int carsId) {
        this.carsId = carsId;
    }
    public int getRoutesId() {
        return this.routesId;
    }
    
    public void setRoutesId(int routesId) {
        this.routesId = routesId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CarHasRoutesId) ) return false;
		 CarHasRoutesId castOther = ( CarHasRoutesId ) other; 
         
		 return (this.getCarsId()==castOther.getCarsId())
 && (this.getRoutesId()==castOther.getRoutesId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCarsId();
         result = 37 * result + this.getRoutesId();
         return result;
   }   


}


