package pojos;
// Generated May 6, 2018 4:40:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CarHasRoutes generated by hbm2java
 */
public class CarHasRoutes  implements java.io.Serializable {


     private CarHasRoutesId id;
     private Cars cars;
     private Routes routes;
     private int id_1;
     private int rent;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;
     private Set orderses = new HashSet(0);

    public CarHasRoutes() {
    }

	
    public CarHasRoutes(CarHasRoutesId id, Cars cars, Routes routes, int id_1, int rent, Date createdAt) {
        this.id = id;
        this.cars = cars;
        this.routes = routes;
        this.id_1 = id_1;
        this.rent = rent;
        this.createdAt = createdAt;
    }
    public CarHasRoutes(CarHasRoutesId id, Cars cars, Routes routes, int id_1, int rent, Date createdAt, Date updatedAt, Date deletedAt, Set orderses) {
       this.id = id;
       this.cars = cars;
       this.routes = routes;
       this.id_1 = id_1;
       this.rent = rent;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
       this.orderses = orderses;
    }
   
    public CarHasRoutesId getId() {
        return this.id;
    }
    
    public void setId(CarHasRoutesId id) {
        this.id = id;
    }
    public Cars getCars() {
        return this.cars;
    }
    
    public void setCars(Cars cars) {
        this.cars = cars;
    }
    public Routes getRoutes() {
        return this.routes;
    }
    
    public void setRoutes(Routes routes) {
        this.routes = routes;
    }
    public int getId_1() {
        return this.id_1;
    }
    
    public void setId_1(int id_1) {
        this.id_1 = id_1;
    }
    public int getRent() {
        return this.rent;
    }
    
    public void setRent(int rent) {
        this.rent = rent;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


