package pojos;
// Generated May 6, 2018 4:40:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cars generated by hbm2java
 */
public class Cars  implements java.io.Serializable {


     private int id;
     private String regNo;
     private String model;
     private int seats;
     private Set carHasRouteses = new HashSet(0);

    public Cars() {
    }

	
    public Cars(int id, String regNo, String model, int seats) {
        this.id = id;
        this.regNo = regNo;
        this.model = model;
        this.seats = seats;
    }
    public Cars(int id, String regNo, String model, int seats, Set carHasRouteses) {
       this.id = id;
       this.regNo = regNo;
       this.model = model;
       this.seats = seats;
       this.carHasRouteses = carHasRouteses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRegNo() {
        return this.regNo;
    }
    
    public void setRegNo(String regNo) {
        this.regNo = regNo;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public int getSeats() {
        return this.seats;
    }
    
    public void setSeats(int seats) {
        this.seats = seats;
    }
    public Set getCarHasRouteses() {
        return this.carHasRouteses;
    }
    
    public void setCarHasRouteses(Set carHasRouteses) {
        this.carHasRouteses = carHasRouteses;
    }




}


