package pojos;
// Generated May 6, 2018 4:40:33 PM by Hibernate Tools 4.3.1



/**
 * OrdersId generated by hbm2java
 */
public class OrdersId  implements java.io.Serializable {


     private int usersId;
     private int schedulesId;
     private int carsId;
     private int routesId;

    public OrdersId() {
    }

    public OrdersId(int usersId, int schedulesId, int carsId, int routesId) {
       this.usersId = usersId;
       this.schedulesId = schedulesId;
       this.carsId = carsId;
       this.routesId = routesId;
    }
   
    public int getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }
    public int getSchedulesId() {
        return this.schedulesId;
    }
    
    public void setSchedulesId(int schedulesId) {
        this.schedulesId = schedulesId;
    }
    public int getCarsId() {
        return this.carsId;
    }
    
    public void setCarsId(int carsId) {
        this.carsId = carsId;
    }
    public int getRoutesId() {
        return this.routesId;
    }
    
    public void setRoutesId(int routesId) {
        this.routesId = routesId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdersId) ) return false;
		 OrdersId castOther = ( OrdersId ) other; 
         
		 return (this.getUsersId()==castOther.getUsersId())
 && (this.getSchedulesId()==castOther.getSchedulesId())
 && (this.getCarsId()==castOther.getCarsId())
 && (this.getRoutesId()==castOther.getRoutesId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsersId();
         result = 37 * result + this.getSchedulesId();
         result = 37 * result + this.getCarsId();
         result = 37 * result + this.getRoutesId();
         return result;
   }   


}


