package pojos;
// Generated May 6, 2018 4:40:33 PM by Hibernate Tools 4.3.1



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private OrdersId id;
     private CarHasRoutes carHasRoutes;
     private Schedules schedules;
     private Users users;
     private int id_1;
     private boolean status;

    public Orders() {
    }

    public Orders(OrdersId id, CarHasRoutes carHasRoutes, Schedules schedules, Users users, int id_1, boolean status) {
       this.id = id;
       this.carHasRoutes = carHasRoutes;
       this.schedules = schedules;
       this.users = users;
       this.id_1 = id_1;
       this.status = status;
    }
   
    public OrdersId getId() {
        return this.id;
    }
    
    public void setId(OrdersId id) {
        this.id = id;
    }
    public CarHasRoutes getCarHasRoutes() {
        return this.carHasRoutes;
    }
    
    public void setCarHasRoutes(CarHasRoutes carHasRoutes) {
        this.carHasRoutes = carHasRoutes;
    }
    public Schedules getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Schedules schedules) {
        this.schedules = schedules;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getId_1() {
        return this.id_1;
    }
    
    public void setId_1(int id_1) {
        this.id_1 = id_1;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


