package pojos;
// Generated May 6, 2018 4:40:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Routes generated by hbm2java
 */
public class Routes  implements java.io.Serializable {


     private int id;
     private String fromCity;
     private String toCity;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;
     private Set carHasRouteses = new HashSet(0);

    public Routes() {
    }

	
    public Routes(int id, String fromCity, Date createdAt) {
        this.id = id;
        this.fromCity = fromCity;
        this.createdAt = createdAt;
    }
    public Routes(int id, String fromCity, String toCity, Date createdAt, Date updatedAt, Date deletedAt, Set carHasRouteses) {
       this.id = id;
       this.fromCity = fromCity;
       this.toCity = toCity;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
       this.carHasRouteses = carHasRouteses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFromCity() {
        return this.fromCity;
    }
    
    public void setFromCity(String fromCity) {
        this.fromCity = fromCity;
    }
    public String getToCity() {
        return this.toCity;
    }
    
    public void setToCity(String toCity) {
        this.toCity = toCity;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
    public Set getCarHasRouteses() {
        return this.carHasRouteses;
    }
    
    public void setCarHasRouteses(Set carHasRouteses) {
        this.carHasRouteses = carHasRouteses;
    }




}


