package pojos;
// Generated May 6, 2018 4:40:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Schedules generated by hbm2java
 */
public class Schedules  implements java.io.Serializable {


     private int id;
     private Date start;
     private Date end;
     private Date createdAt;
     private Date updatedAt;
     private Date deletedAt;
     private Set orderses = new HashSet(0);

    public Schedules() {
    }

	
    public Schedules(int id, Date start, Date createdAt) {
        this.id = id;
        this.start = start;
        this.createdAt = createdAt;
    }
    public Schedules(int id, Date start, Date end, Date createdAt, Date updatedAt, Date deletedAt, Set orderses) {
       this.id = id;
       this.start = start;
       this.end = end;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.deletedAt = deletedAt;
       this.orderses = orderses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Date getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


